application:
  name: uniaopic
  project: uniaopic
  publicly_accessible: true
  organization: QoveryCommunity
routers:
- name: main
  custom_domains:
  - branch: master
    domain: uniao.edelans.com
  routes:
  - application_name: uniaopic
    paths:
    - /
